/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_parky (void)
{
  GtkWidget *parky;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *button_affectp_welcome;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label12;
  GtkWidget *button_deletep_welcome;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label11;
  GtkWidget *button_modifyp_welcome;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label10;
  GtkWidget *button_wiewp_welcome;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label9;
  GtkWidget *button_addp_welcome;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label8;
  GtkWidget *image31;
  GtkWidget *image33;
  GtkWidget *image32;
  GtkWidget *label1;
  GtkWidget *fixed3;
  GtkWidget *entry_idp_add;
  GtkWidget *entry_locationp_add;
  GtkObject *spin_tsp_add_adj;
  GtkWidget *spin_tsp_add;
  GtkObject *spin_asp_add_adj;
  GtkWidget *spin_asp_add;
  GtkWidget *entry_pricep_add;
  GtkWidget *calendaryosr1;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *radio_covered_add;
  GSList *radio_covered_add_group = NULL;
  GtkWidget *radio_uncovered_add;
  GtkWidget *check_moto_add;
  GtkWidget *check_trucks_add;
  GtkWidget *check_cars_add;
  GtkWidget *label13;
  GtkWidget *button_savep_add;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image16;
  GtkWidget *label35;
  GtkWidget *refresh_yosr1;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image27;
  GtkWidget *label47;
  GtkWidget *button_cancelp_add;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image17;
  GtkWidget *label36;
  GtkWidget *image8;
  GtkWidget *label2;
  GtkWidget *fixed4;
  GtkWidget *treeview_parkingsyosr;
  GtkWidget *label21;
  GtkWidget *image29;
  GtkWidget *button_cancelp_view;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image10;
  GtkWidget *label23;
  GtkWidget *display_view_yosr;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image25;
  GtkWidget *label45;
  GtkWidget *button_refreshp_view;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image9;
  GtkWidget *label22;
  GtkWidget *label3;
  GtkWidget *fixed5;
  GtkWidget *entry_idp_modify;
  GtkWidget *entry_locationp_modify;
  GtkObject *spin_tsp_modify_adj;
  GtkWidget *spin_tsp_modify;
  GtkObject *spin_asp_modify_adj;
  GtkWidget *spin_asp_modify;
  GtkWidget *entry_pricep_modify;
  GtkWidget *label24;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *calendaryosr1_modify;
  GtkWidget *label_found_yosr;
  GtkWidget *label26;
  GtkWidget *button_searchpyosr;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label25;
  GtkWidget *radio_covered_modify;
  GSList *radio_covered_modify_group = NULL;
  GtkWidget *radio_uncovered_modify;
  GtkWidget *check_cars_modify;
  GtkWidget *check_moto_modify;
  GtkWidget *check_trucks_modify;
  GtkWidget *image13;
  GtkWidget *button_cancelp_modif;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image15;
  GtkWidget *label34;
  GtkWidget *refresh_yosr2;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image28;
  GtkWidget *label48;
  GtkWidget *button_modif_modif;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image14;
  GtkWidget *label33;
  GtkWidget *label4;
  GtkWidget *fixed6;
  GtkWidget *entry_idp_delete;
  GtkWidget *label37;
  GtkWidget *button_deletep_delete;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image19;
  GtkWidget *label38;
  GtkWidget *button_cancelp_delete;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image20;
  GtkWidget *label39;
  GtkWidget *image30;
  GtkWidget *search_yosr_delete;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image26;
  GtkWidget *label46;
  GtkWidget *label5;
  GtkWidget *fixed8;
  GtkWidget *label_affect_agent;
  GtkWidget *label41;
  GtkWidget *combo_yosr_parking;
  GtkWidget *label42;
  GtkWidget *image22;
  GtkWidget *button_affect_affect;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image23;
  GtkWidget *label43;
  GtkWidget *button_cancelp_cancel;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image24;
  GtkWidget *label44;
  GtkWidget *refresh_yosr3;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image34;
  GtkWidget *label49;
  GtkWidget *image35;
  GtkWidget *combo_yosr_agent;
  GtkWidget *label6;

  parky = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (parky), _("PARKING MANAGEMENT"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (parky), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1432, 792);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  button_affectp_welcome = gtk_button_new ();
  gtk_widget_show (button_affectp_welcome);
  gtk_fixed_put (GTK_FIXED (fixed2), button_affectp_welcome, 1240, 656);
  gtk_widget_set_size_request (button_affectp_welcome, 114, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_affectp_welcome), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("AFFECT"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  button_deletep_welcome = gtk_button_new ();
  gtk_widget_show (button_deletep_welcome);
  gtk_fixed_put (GTK_FIXED (fixed2), button_deletep_welcome, 1240, 544);
  gtk_widget_set_size_request (button_deletep_welcome, 112, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_deletep_welcome), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("DELETE"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox5), label11, FALSE, FALSE, 0);

  button_modifyp_welcome = gtk_button_new ();
  gtk_widget_show (button_modifyp_welcome);
  gtk_fixed_put (GTK_FIXED (fixed2), button_modifyp_welcome, 1240, 432);
  gtk_widget_set_size_request (button_modifyp_welcome, 120, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_modifyp_welcome), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("MODIFY"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox4), label10, FALSE, FALSE, 0);

  button_wiewp_welcome = gtk_button_new ();
  gtk_widget_show (button_wiewp_welcome);
  gtk_fixed_put (GTK_FIXED (fixed2), button_wiewp_welcome, 1240, 336);
  gtk_widget_set_size_request (button_wiewp_welcome, 120, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_wiewp_welcome), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-leave-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("VIEW"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox3), label9, FALSE, FALSE, 0);

  button_addp_welcome = gtk_button_new ();
  gtk_widget_show (button_addp_welcome);
  gtk_fixed_put (GTK_FIXED (fixed2), button_addp_welcome, 1240, 232);
  gtk_widget_set_size_request (button_addp_welcome, 120, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_addp_welcome), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("ADD"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);

  image31 = create_pixmap (parky, "images (1).jpeg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed2), image31, 0, 216);
  gtk_widget_set_size_request (image31, 1208, 760);

  image33 = create_pixmap (parky, "images (1).jpeg");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed2), image33, 1152, 0);
  gtk_widget_set_size_request (image33, 264, 200);

  image32 = create_pixmap (parky, "landscape_parking_management_edited.jpg");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed2), image32, 0, 0);
  gtk_widget_set_size_request (image32, 1280, 776);
  gtk_misc_set_alignment (GTK_MISC (image32), 0.5, 0);

  label1 = gtk_label_new (_("<span color=\"#C89F9C\"><b>WELCOME</b></span>"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_widget_set_size_request (label1, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry_idp_add = gtk_entry_new ();
  gtk_widget_show (entry_idp_add);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_idp_add, 168, 32);
  gtk_widget_set_size_request (entry_idp_add, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idp_add), 8226);

  entry_locationp_add = gtk_entry_new ();
  gtk_widget_show (entry_locationp_add);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_locationp_add, 168, 96);
  gtk_widget_set_size_request (entry_locationp_add, 232, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_locationp_add), 8226);

  spin_tsp_add_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_tsp_add = gtk_spin_button_new (GTK_ADJUSTMENT (spin_tsp_add_adj), 1, 0);
  gtk_widget_show (spin_tsp_add);
  gtk_fixed_put (GTK_FIXED (fixed3), spin_tsp_add, 240, 224);
  gtk_widget_set_size_request (spin_tsp_add, 60, 27);

  spin_asp_add_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_asp_add = gtk_spin_button_new (GTK_ADJUSTMENT (spin_asp_add_adj), 1, 0);
  gtk_widget_show (spin_asp_add);
  gtk_fixed_put (GTK_FIXED (fixed3), spin_asp_add, 240, 304);
  gtk_widget_set_size_request (spin_asp_add, 60, 27);

  entry_pricep_add = gtk_entry_new ();
  gtk_widget_show (entry_pricep_add);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_pricep_add, 176, 400);
  gtk_widget_set_size_request (entry_pricep_add, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_pricep_add), 8226);

  calendaryosr1 = gtk_calendar_new ();
  gtk_widget_show (calendaryosr1);
  gtk_fixed_put (GTK_FIXED (fixed3), calendaryosr1, 904, 80);
  gtk_widget_set_size_request (calendaryosr1, 266, 210);
  gtk_calendar_display_options (GTK_CALENDAR (calendaryosr1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label14 = gtk_label_new (_("<span color=\"#137C8B\"><b>Location :</b></span>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 24, 120);
  gtk_widget_set_size_request (label14, 112, 24);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  label15 = gtk_label_new (_("<span color=\"#137C8B\"><b>Total number \n      of spaces :</b></span>"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed3), label15, 0, 208);
  gtk_widget_set_size_request (label15, 192, 64);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  label16 = gtk_label_new (_("<span color=\"#137C8B\"><b>Available spaces :</b></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed3), label16, 0, 280);
  gtk_widget_set_size_request (label16, 168, 88);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  label17 = gtk_label_new (_("<span color=\"#137C8B\"><b>Price per hour :</b></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 0, 392);
  gtk_widget_set_size_request (label17, 152, 40);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("<span color=\"#137C8B\"><b>Parking state :</b></span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 0, 488);
  gtk_widget_set_size_request (label18, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label19 = gtk_label_new (_("<span color=\"#137C8B\"><b>Type of\n available spaces :</b></span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 0, 528);
  gtk_widget_set_size_request (label19, 144, 72);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("<span color=\"#137C8B\"><b>Select the opening day of the parking lots :</b></span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 856, 16);
  gtk_widget_set_size_request (label20, 344, 40);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  radio_covered_add = gtk_radio_button_new_with_mnemonic (NULL, _("Covered"));
  gtk_widget_show (radio_covered_add);
  gtk_fixed_put (GTK_FIXED (fixed3), radio_covered_add, 176, 488);
  gtk_widget_set_size_request (radio_covered_add, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_covered_add), radio_covered_add_group);
  radio_covered_add_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_covered_add));

  radio_uncovered_add = gtk_radio_button_new_with_mnemonic (NULL, _("Uncovered"));
  gtk_widget_show (radio_uncovered_add);
  gtk_fixed_put (GTK_FIXED (fixed3), radio_uncovered_add, 360, 488);
  gtk_widget_set_size_request (radio_uncovered_add, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_uncovered_add), radio_covered_add_group);
  radio_covered_add_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_uncovered_add));

  check_moto_add = gtk_check_button_new_with_mnemonic (_("Motorcycles"));
  gtk_widget_show (check_moto_add);
  gtk_fixed_put (GTK_FIXED (fixed3), check_moto_add, 312, 560);
  gtk_widget_set_size_request (check_moto_add, 118, 24);

  check_trucks_add = gtk_check_button_new_with_mnemonic (_("Trucks"));
  gtk_widget_show (check_trucks_add);
  gtk_fixed_put (GTK_FIXED (fixed3), check_trucks_add, 480, 560);
  gtk_widget_set_size_request (check_trucks_add, 118, 24);

  check_cars_add = gtk_check_button_new_with_mnemonic (_("Cars"));
  gtk_widget_show (check_cars_add);
  gtk_fixed_put (GTK_FIXED (fixed3), check_cars_add, 176, 560);
  gtk_widget_set_size_request (check_cars_add, 118, 24);

  label13 = gtk_label_new (_("<span color=\"#137C8B\"><b>ID parking :</b></span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 8, 24);
  gtk_widget_set_size_request (label13, 136, 40);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  button_savep_add = gtk_button_new ();
  gtk_widget_show (button_savep_add);
  gtk_fixed_put (GTK_FIXED (fixed3), button_savep_add, 80, 632);
  gtk_widget_set_size_request (button_savep_add, 136, 48);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_savep_add), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image16 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox12), image16, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("SAVE"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox12), label35, FALSE, FALSE, 0);

  refresh_yosr1 = gtk_button_new ();
  gtk_widget_show (refresh_yosr1);
  gtk_fixed_put (GTK_FIXED (fixed3), refresh_yosr1, 384, 632);
  gtk_widget_set_size_request (refresh_yosr1, 144, 48);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (refresh_yosr1), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image27 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox20), image27, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("REFRESH"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox20), label47, FALSE, FALSE, 0);

  button_cancelp_add = gtk_button_new ();
  gtk_widget_show (button_cancelp_add);
  gtk_fixed_put (GTK_FIXED (fixed3), button_cancelp_add, 232, 704);
  gtk_widget_set_size_request (button_cancelp_add, 136, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_cancelp_add), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image17 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox13), image17, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("CANCEL"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox13), label36, FALSE, FALSE, 0);

  image8 = create_pixmap (parky, "carparking-01-01.png");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed3), image8, 560, 0);
  gtk_widget_set_size_request (image8, 1216, 1368);

  label2 = gtk_label_new (_("<span color=\"#C89F9C\"><b>ADD</b></span>"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_widget_set_size_request (label2, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview_parkingsyosr = gtk_tree_view_new ();
  gtk_widget_show (treeview_parkingsyosr);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview_parkingsyosr, 296, 104);
  gtk_widget_set_size_request (treeview_parkingsyosr, 880, 320);

  label21 = gtk_label_new (_("<span color=\"#137C8B\"><b>THE LIST OF PARKING LOTS  </b></span>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 128, 0);
  gtk_widget_set_size_request (label21, 1008, 112);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  image29 = create_pixmap (parky, "AFRC-ACADEMIE.png");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed4), image29, 0, 104);
  gtk_widget_set_size_request (image29, 1416, 544);

  button_cancelp_view = gtk_button_new ();
  gtk_widget_show (button_cancelp_view);
  gtk_fixed_put (GTK_FIXED (fixed4), button_cancelp_view, 616, 696);
  gtk_widget_set_size_request (button_cancelp_view, 136, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_cancelp_view), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox8), image10, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("CANCEL"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox8), label23, FALSE, FALSE, 0);

  display_view_yosr = gtk_button_new ();
  gtk_widget_show (display_view_yosr);
  gtk_fixed_put (GTK_FIXED (fixed4), display_view_yosr, 872, 664);
  gtk_widget_set_size_request (display_view_yosr, 136, 48);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (display_view_yosr), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image25 = gtk_image_new_from_stock ("gtk-fullscreen", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox18), image25, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("DISPLAY"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox18), label45, FALSE, FALSE, 0);

  button_refreshp_view = gtk_button_new ();
  gtk_widget_show (button_refreshp_view);
  gtk_fixed_put (GTK_FIXED (fixed4), button_refreshp_view, 376, 664);
  gtk_widget_set_size_request (button_refreshp_view, 128, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_refreshp_view), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image9 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox7), image9, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("REFRESH"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox7), label22, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("<span color=\"#C89F9C\"><b>VIEW</b></span>"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label3);
  gtk_widget_set_size_request (label3, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label3), TRUE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  entry_idp_modify = gtk_entry_new ();
  gtk_widget_show (entry_idp_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_idp_modify, 288, 32);
  gtk_widget_set_size_request (entry_idp_modify, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idp_modify), 8226);

  entry_locationp_modify = gtk_entry_new ();
  gtk_widget_show (entry_locationp_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_locationp_modify, 288, 112);
  gtk_widget_set_size_request (entry_locationp_modify, 224, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_locationp_modify), 8226);

  spin_tsp_modify_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_tsp_modify = gtk_spin_button_new (GTK_ADJUSTMENT (spin_tsp_modify_adj), 1, 0);
  gtk_widget_show (spin_tsp_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), spin_tsp_modify, 344, 256);
  gtk_widget_set_size_request (spin_tsp_modify, 60, 27);

  spin_asp_modify_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spin_asp_modify = gtk_spin_button_new (GTK_ADJUSTMENT (spin_asp_modify_adj), 1, 0);
  gtk_widget_show (spin_asp_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), spin_asp_modify, 344, 344);
  gtk_widget_set_size_request (spin_asp_modify, 60, 27);

  entry_pricep_modify = gtk_entry_new ();
  gtk_widget_show (entry_pricep_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_pricep_modify, 296, 424);
  gtk_widget_set_size_request (entry_pricep_modify, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_pricep_modify), 8226);

  label24 = gtk_label_new (_("<span color=\"#137C8B\"><b>ID parking to modify :</b></span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 0, 24);
  gtk_widget_set_size_request (label24, 288, 56);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label27 = gtk_label_new (_("<span color=\"#137C8B\"><b>Total number \n      of spaces :</b></span>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 16, 224);
  gtk_widget_set_size_request (label27, 208, 96);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  label28 = gtk_label_new (_("<span color=\"#137C8B\"><b>Available spaces :</b></span>"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 16, 328);
  gtk_widget_set_size_request (label28, 184, 64);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  label29 = gtk_label_new (_("<span color=\"#137C8B\"><b>Price per hour :</b></span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 8, 408);
  gtk_widget_set_size_request (label29, 184, 64);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label30 = gtk_label_new (_("<span color=\"#137C8B\"><b>Parking state :</b></span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 8, 504);
  gtk_widget_set_size_request (label30, 184, 48);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label31 = gtk_label_new (_("<span color=\"#137C8B\"><b>Type of\n available spaces :</b></span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 24, 584);
  gtk_widget_set_size_request (label31, 160, 48);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  label32 = gtk_label_new (_("<span color=\"#137C8B\"><b>Select the opening day of the parking lots :</b></span>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 888, 0);
  gtk_widget_set_size_request (label32, 368, 72);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  calendaryosr1_modify = gtk_calendar_new ();
  gtk_widget_show (calendaryosr1_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), calendaryosr1_modify, 944, 88);
  gtk_widget_set_size_request (calendaryosr1_modify, 266, 218);
  gtk_calendar_display_options (GTK_CALENDAR (calendaryosr1_modify),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label_found_yosr = gtk_label_new ("");
  gtk_widget_show (label_found_yosr);
  gtk_fixed_put (GTK_FIXED (fixed5), label_found_yosr, 592, 32);
  gtk_widget_set_size_request (label_found_yosr, 128, 24);

  label26 = gtk_label_new (_("<span color=\"#137C8B\"><b>Location :</b></span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 24, 120);
  gtk_widget_set_size_request (label26, 192, 64);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  button_searchpyosr = gtk_button_new ();
  gtk_widget_show (button_searchpyosr);
  gtk_fixed_put (GTK_FIXED (fixed5), button_searchpyosr, 472, 24);
  gtk_widget_set_size_request (button_searchpyosr, 104, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_searchpyosr), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("SEARCH"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox9), label25, FALSE, FALSE, 0);

  radio_covered_modify = gtk_radio_button_new_with_mnemonic (NULL, _("Covered"));
  gtk_widget_show (radio_covered_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), radio_covered_modify, 288, 512);
  gtk_widget_set_size_request (radio_covered_modify, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_covered_modify), radio_covered_modify_group);
  radio_covered_modify_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_covered_modify));

  radio_uncovered_modify = gtk_radio_button_new_with_mnemonic (NULL, _("Uncovered"));
  gtk_widget_show (radio_uncovered_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), radio_uncovered_modify, 512, 512);
  gtk_widget_set_size_request (radio_uncovered_modify, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio_uncovered_modify), radio_covered_modify_group);
  radio_covered_modify_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio_uncovered_modify));

  check_cars_modify = gtk_check_button_new_with_mnemonic (_("Cars"));
  gtk_widget_show (check_cars_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), check_cars_modify, 264, 600);
  gtk_widget_set_size_request (check_cars_modify, 118, 24);

  check_moto_modify = gtk_check_button_new_with_mnemonic (_("Motorcycles"));
  gtk_widget_show (check_moto_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), check_moto_modify, 440, 600);
  gtk_widget_set_size_request (check_moto_modify, 118, 24);

  check_trucks_modify = gtk_check_button_new_with_mnemonic (_("Trucks"));
  gtk_widget_show (check_trucks_modify);
  gtk_fixed_put (GTK_FIXED (fixed5), check_trucks_modify, 616, 600);
  gtk_widget_set_size_request (check_trucks_modify, 118, 24);

  image13 = create_pixmap (parky, "carparking-01-01.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed5), image13, 680, 0);
  gtk_widget_set_size_request (image13, 968, 1224);

  button_cancelp_modif = gtk_button_new ();
  gtk_widget_show (button_cancelp_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), button_cancelp_modif, 296, 696);
  gtk_widget_set_size_request (button_cancelp_modif, 128, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_cancelp_modif), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox11), image15, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("CANCEL"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox11), label34, FALSE, FALSE, 0);

  refresh_yosr2 = gtk_button_new ();
  gtk_widget_show (refresh_yosr2);
  gtk_fixed_put (GTK_FIXED (fixed5), refresh_yosr2, 480, 656);
  gtk_widget_set_size_request (refresh_yosr2, 120, 48);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (refresh_yosr2), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image28 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox21), image28, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("REFRESH"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox21), label48, FALSE, FALSE, 0);

  button_modif_modif = gtk_button_new ();
  gtk_widget_show (button_modif_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), button_modif_modif, 120, 656);
  gtk_widget_set_size_request (button_modif_modif, 120, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_modif_modif), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox10), image14, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("MODIFY"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox10), label33, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("<span color=\"#C89F9C\"><b>MODIFY</b></span>"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label4);
  gtk_widget_set_size_request (label4, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label4), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  entry_idp_delete = gtk_entry_new ();
  gtk_widget_show (entry_idp_delete);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_idp_delete, 680, 40);
  gtk_widget_set_size_request (entry_idp_delete, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_idp_delete), 8226);

  label37 = gtk_label_new (_("<span color=\"#137C8B\"><b>ID parking to delete :</b></span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 464, 32);
  gtk_widget_set_size_request (label37, 184, 56);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  button_deletep_delete = gtk_button_new ();
  gtk_widget_show (button_deletep_delete);
  gtk_fixed_put (GTK_FIXED (fixed6), button_deletep_delete, 968, 280);
  gtk_widget_set_size_request (button_deletep_delete, 144, 45);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_deletep_delete), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image19 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox14), image19, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("DELETE"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox14), label38, FALSE, FALSE, 0);

  button_cancelp_delete = gtk_button_new ();
  gtk_widget_show (button_cancelp_delete);
  gtk_fixed_put (GTK_FIXED (fixed6), button_cancelp_delete, 1240, 280);
  gtk_widget_set_size_request (button_cancelp_delete, 144, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_cancelp_delete), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image20 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox15), image20, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("CANCEL"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox15), label39, FALSE, FALSE, 0);

  image30 = create_pixmap (parky, "ParkyAI.png");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed6), image30, 0, 64);
  gtk_widget_set_size_request (image30, 1416, 696);
  gtk_misc_set_alignment (GTK_MISC (image30), 1, 0.22);
  gtk_misc_set_padding (GTK_MISC (image30), 169, 0);

  search_yosr_delete = gtk_button_new ();
  gtk_widget_show (search_yosr_delete);
  gtk_fixed_put (GTK_FIXED (fixed6), search_yosr_delete, 896, 40);
  gtk_widget_set_size_request (search_yosr_delete, 128, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (search_yosr_delete), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image26 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox19), image26, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("SEARCH"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox19), label46, FALSE, FALSE, 0);

  label5 = gtk_label_new (_("<span color=\"#C89F9C\"><b>DELETE</b></span>"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label5);
  gtk_widget_set_size_request (label5, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  label_affect_agent = gtk_label_new ("");
  gtk_widget_show (label_affect_agent);
  gtk_fixed_put (GTK_FIXED (fixed8), label_affect_agent, 48, 240);
  gtk_widget_set_size_request (label_affect_agent, 432, 80);

  label41 = gtk_label_new (_("<span color=\"#137C8B\"><b>ID agent to affect  :</b></span>"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed8), label41, 0, 88);
  gtk_widget_set_size_request (label41, 277, 40);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  combo_yosr_parking = gtk_combo_box_new_text ();
  gtk_widget_show (combo_yosr_parking);
  gtk_fixed_put (GTK_FIXED (fixed8), combo_yosr_parking, 280, 240);
  gtk_widget_set_size_request (combo_yosr_parking, 195, 38);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_parking), _("1APARK"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_parking), _("2BPARK"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_parking), _("3CPARK"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_parking), _("4DPARK"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_parking), _("5DPARK"));

  label42 = gtk_label_new (_("<span color=\"#137C8B\"><b>ID parking available :</b></span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed8), label42, 48, 240);
  gtk_widget_set_size_request (label42, 184, 48);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  image22 = create_pixmap (parky, "R.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed8), image22, 792, 0);
  gtk_widget_set_size_request (image22, 640, 752);

  button_affect_affect = gtk_button_new ();
  gtk_widget_show (button_affect_affect);
  gtk_fixed_put (GTK_FIXED (fixed8), button_affect_affect, 96, 592);
  gtk_widget_set_size_request (button_affect_affect, 120, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_affect_affect), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image23 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox16), image23, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("AFFECT"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox16), label43, FALSE, FALSE, 0);

  button_cancelp_cancel = gtk_button_new ();
  gtk_widget_show (button_cancelp_cancel);
  gtk_fixed_put (GTK_FIXED (fixed8), button_cancelp_cancel, 280, 680);
  gtk_widget_set_size_request (button_cancelp_cancel, 120, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_cancelp_cancel), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image24 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox17), image24, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("CANCEL"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox17), label44, FALSE, FALSE, 0);

  refresh_yosr3 = gtk_button_new ();
  gtk_widget_show (refresh_yosr3);
  gtk_fixed_put (GTK_FIXED (fixed8), refresh_yosr3, 488, 592);
  gtk_widget_set_size_request (refresh_yosr3, 112, 40);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (refresh_yosr3), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image34 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox22), image34, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("REFRESH"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox22), label49, FALSE, FALSE, 0);

  image35 = create_pixmap (parky, "images (2).jpeg");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed8), image35, 0, 328);
  gtk_widget_set_size_request (image35, 712, 272);

  combo_yosr_agent = gtk_combo_box_new_text ();
  gtk_widget_show (combo_yosr_agent);
  gtk_fixed_put (GTK_FIXED (fixed8), combo_yosr_agent, 280, 88);
  gtk_widget_set_size_request (combo_yosr_agent, 193, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_agent), _("1agtA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_agent), _("2agtB"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_agent), _("3agtC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_agent), _("4agtD"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combo_yosr_agent), _("5agtE"));

  label6 = gtk_label_new (_("<span color=\"#C89F9C\"><b>AFFECT</b></span>"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label6);
  gtk_widget_set_size_request (label6, 80, 25);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  g_signal_connect ((gpointer) button_affectp_welcome, "clicked",
                    G_CALLBACK (on_button_affectp_welcome_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_deletep_welcome, "clicked",
                    G_CALLBACK (on_button_deletep_welcome_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifyp_welcome, "clicked",
                    G_CALLBACK (on_button_modifyp_welcome_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_wiewp_welcome, "clicked",
                    G_CALLBACK (on_button_wiewp_welcome_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_addp_welcome, "clicked",
                    G_CALLBACK (on_button_addp_welcome_clicked),
                    NULL);
  g_signal_connect ((gpointer) radio_covered_add, "toggled",
                    G_CALLBACK (on_radio_covered_add_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_uncovered_add, "toggled",
                    G_CALLBACK (on_radio_uncovered_add_toggled),
                    NULL);
  g_signal_connect ((gpointer) check_moto_add, "toggled",
                    G_CALLBACK (on_check_moto_add_toggled),
                    NULL);
  g_signal_connect ((gpointer) check_trucks_add, "toggled",
                    G_CALLBACK (on_check_trucks_add_toggled),
                    NULL);
  g_signal_connect ((gpointer) check_cars_add, "toggled",
                    G_CALLBACK (on_check_cars_add_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_savep_add, "clicked",
                    G_CALLBACK (on_button_savep_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh_yosr1, "clicked",
                    G_CALLBACK (on_refresh_yosr1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cancelp_add, "clicked",
                    G_CALLBACK (on_button_cancelp_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cancelp_view, "clicked",
                    G_CALLBACK (on_button_cancelp_view_clicked),
                    NULL);
  g_signal_connect ((gpointer) display_view_yosr, "clicked",
                    G_CALLBACK (on_display_view_yosr_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_refreshp_view, "clicked",
                    G_CALLBACK (on_button_refreshp_view_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_searchpyosr, "clicked",
                    G_CALLBACK (on_button_searchpyosr_clicked),
                    NULL);
  g_signal_connect ((gpointer) radio_covered_modify, "toggled",
                    G_CALLBACK (on_radio_covered_motify_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio_uncovered_modify, "toggled",
                    G_CALLBACK (on_radio_uncovered_modify_toggled),
                    NULL);
  g_signal_connect ((gpointer) check_cars_modify, "toggled",
                    G_CALLBACK (on_check_cars_modify_toggled),
                    NULL);
  g_signal_connect ((gpointer) check_moto_modify, "toggled",
                    G_CALLBACK (on_check_moto_modify_toggled),
                    NULL);
  g_signal_connect ((gpointer) check_trucks_modify, "toggled",
                    G_CALLBACK (on_check_trucks_modify_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_cancelp_modif, "clicked",
                    G_CALLBACK (on_button_cancelp_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh_yosr2, "clicked",
                    G_CALLBACK (on_refresh_yosr2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modif_modif, "clicked",
                    G_CALLBACK (on_button_modif_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_deletep_delete, "clicked",
                    G_CALLBACK (on_button_deletep_delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cancelp_delete, "clicked",
                    G_CALLBACK (on_button_cancelp_delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) search_yosr_delete, "clicked",
                    G_CALLBACK (on_search_yosr_delete_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affect_affect, "clicked",
                    G_CALLBACK (on_button_affect_affect_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_cancelp_cancel, "clicked",
                    G_CALLBACK (on_button_cancelp_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh_yosr3, "clicked",
                    G_CALLBACK (on_refresh_yosr3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (parky, parky, "parky");
  GLADE_HOOKUP_OBJECT (parky, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (parky, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (parky, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (parky, button_affectp_welcome, "button_affectp_welcome");
  GLADE_HOOKUP_OBJECT (parky, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (parky, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (parky, image7, "image7");
  GLADE_HOOKUP_OBJECT (parky, label12, "label12");
  GLADE_HOOKUP_OBJECT (parky, button_deletep_welcome, "button_deletep_welcome");
  GLADE_HOOKUP_OBJECT (parky, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (parky, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (parky, image6, "image6");
  GLADE_HOOKUP_OBJECT (parky, label11, "label11");
  GLADE_HOOKUP_OBJECT (parky, button_modifyp_welcome, "button_modifyp_welcome");
  GLADE_HOOKUP_OBJECT (parky, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (parky, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (parky, image5, "image5");
  GLADE_HOOKUP_OBJECT (parky, label10, "label10");
  GLADE_HOOKUP_OBJECT (parky, button_wiewp_welcome, "button_wiewp_welcome");
  GLADE_HOOKUP_OBJECT (parky, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (parky, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (parky, image4, "image4");
  GLADE_HOOKUP_OBJECT (parky, label9, "label9");
  GLADE_HOOKUP_OBJECT (parky, button_addp_welcome, "button_addp_welcome");
  GLADE_HOOKUP_OBJECT (parky, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (parky, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (parky, image3, "image3");
  GLADE_HOOKUP_OBJECT (parky, label8, "label8");
  GLADE_HOOKUP_OBJECT (parky, image31, "image31");
  GLADE_HOOKUP_OBJECT (parky, image33, "image33");
  GLADE_HOOKUP_OBJECT (parky, image32, "image32");
  GLADE_HOOKUP_OBJECT (parky, label1, "label1");
  GLADE_HOOKUP_OBJECT (parky, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (parky, entry_idp_add, "entry_idp_add");
  GLADE_HOOKUP_OBJECT (parky, entry_locationp_add, "entry_locationp_add");
  GLADE_HOOKUP_OBJECT (parky, spin_tsp_add, "spin_tsp_add");
  GLADE_HOOKUP_OBJECT (parky, spin_asp_add, "spin_asp_add");
  GLADE_HOOKUP_OBJECT (parky, entry_pricep_add, "entry_pricep_add");
  GLADE_HOOKUP_OBJECT (parky, calendaryosr1, "calendaryosr1");
  GLADE_HOOKUP_OBJECT (parky, label14, "label14");
  GLADE_HOOKUP_OBJECT (parky, label15, "label15");
  GLADE_HOOKUP_OBJECT (parky, label16, "label16");
  GLADE_HOOKUP_OBJECT (parky, label17, "label17");
  GLADE_HOOKUP_OBJECT (parky, label18, "label18");
  GLADE_HOOKUP_OBJECT (parky, label19, "label19");
  GLADE_HOOKUP_OBJECT (parky, label20, "label20");
  GLADE_HOOKUP_OBJECT (parky, radio_covered_add, "radio_covered_add");
  GLADE_HOOKUP_OBJECT (parky, radio_uncovered_add, "radio_uncovered_add");
  GLADE_HOOKUP_OBJECT (parky, check_moto_add, "check_moto_add");
  GLADE_HOOKUP_OBJECT (parky, check_trucks_add, "check_trucks_add");
  GLADE_HOOKUP_OBJECT (parky, check_cars_add, "check_cars_add");
  GLADE_HOOKUP_OBJECT (parky, label13, "label13");
  GLADE_HOOKUP_OBJECT (parky, button_savep_add, "button_savep_add");
  GLADE_HOOKUP_OBJECT (parky, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (parky, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (parky, image16, "image16");
  GLADE_HOOKUP_OBJECT (parky, label35, "label35");
  GLADE_HOOKUP_OBJECT (parky, refresh_yosr1, "refresh_yosr1");
  GLADE_HOOKUP_OBJECT (parky, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (parky, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (parky, image27, "image27");
  GLADE_HOOKUP_OBJECT (parky, label47, "label47");
  GLADE_HOOKUP_OBJECT (parky, button_cancelp_add, "button_cancelp_add");
  GLADE_HOOKUP_OBJECT (parky, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (parky, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (parky, image17, "image17");
  GLADE_HOOKUP_OBJECT (parky, label36, "label36");
  GLADE_HOOKUP_OBJECT (parky, image8, "image8");
  GLADE_HOOKUP_OBJECT (parky, label2, "label2");
  GLADE_HOOKUP_OBJECT (parky, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (parky, treeview_parkingsyosr, "treeview_parkingsyosr");
  GLADE_HOOKUP_OBJECT (parky, label21, "label21");
  GLADE_HOOKUP_OBJECT (parky, image29, "image29");
  GLADE_HOOKUP_OBJECT (parky, button_cancelp_view, "button_cancelp_view");
  GLADE_HOOKUP_OBJECT (parky, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (parky, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (parky, image10, "image10");
  GLADE_HOOKUP_OBJECT (parky, label23, "label23");
  GLADE_HOOKUP_OBJECT (parky, display_view_yosr, "display_view_yosr");
  GLADE_HOOKUP_OBJECT (parky, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (parky, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (parky, image25, "image25");
  GLADE_HOOKUP_OBJECT (parky, label45, "label45");
  GLADE_HOOKUP_OBJECT (parky, button_refreshp_view, "button_refreshp_view");
  GLADE_HOOKUP_OBJECT (parky, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (parky, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (parky, image9, "image9");
  GLADE_HOOKUP_OBJECT (parky, label22, "label22");
  GLADE_HOOKUP_OBJECT (parky, label3, "label3");
  GLADE_HOOKUP_OBJECT (parky, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (parky, entry_idp_modify, "entry_idp_modify");
  GLADE_HOOKUP_OBJECT (parky, entry_locationp_modify, "entry_locationp_modify");
  GLADE_HOOKUP_OBJECT (parky, spin_tsp_modify, "spin_tsp_modify");
  GLADE_HOOKUP_OBJECT (parky, spin_asp_modify, "spin_asp_modify");
  GLADE_HOOKUP_OBJECT (parky, entry_pricep_modify, "entry_pricep_modify");
  GLADE_HOOKUP_OBJECT (parky, label24, "label24");
  GLADE_HOOKUP_OBJECT (parky, label27, "label27");
  GLADE_HOOKUP_OBJECT (parky, label28, "label28");
  GLADE_HOOKUP_OBJECT (parky, label29, "label29");
  GLADE_HOOKUP_OBJECT (parky, label30, "label30");
  GLADE_HOOKUP_OBJECT (parky, label31, "label31");
  GLADE_HOOKUP_OBJECT (parky, label32, "label32");
  GLADE_HOOKUP_OBJECT (parky, calendaryosr1_modify, "calendaryosr1_modify");
  GLADE_HOOKUP_OBJECT (parky, label_found_yosr, "label_found_yosr");
  GLADE_HOOKUP_OBJECT (parky, label26, "label26");
  GLADE_HOOKUP_OBJECT (parky, button_searchpyosr, "button_searchpyosr");
  GLADE_HOOKUP_OBJECT (parky, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (parky, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (parky, image12, "image12");
  GLADE_HOOKUP_OBJECT (parky, label25, "label25");
  GLADE_HOOKUP_OBJECT (parky, radio_covered_modify, "radio_covered_modify");
  GLADE_HOOKUP_OBJECT (parky, radio_uncovered_modify, "radio_uncovered_modify");
  GLADE_HOOKUP_OBJECT (parky, check_cars_modify, "check_cars_modify");
  GLADE_HOOKUP_OBJECT (parky, check_moto_modify, "check_moto_modify");
  GLADE_HOOKUP_OBJECT (parky, check_trucks_modify, "check_trucks_modify");
  GLADE_HOOKUP_OBJECT (parky, image13, "image13");
  GLADE_HOOKUP_OBJECT (parky, button_cancelp_modif, "button_cancelp_modif");
  GLADE_HOOKUP_OBJECT (parky, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (parky, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (parky, image15, "image15");
  GLADE_HOOKUP_OBJECT (parky, label34, "label34");
  GLADE_HOOKUP_OBJECT (parky, refresh_yosr2, "refresh_yosr2");
  GLADE_HOOKUP_OBJECT (parky, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (parky, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (parky, image28, "image28");
  GLADE_HOOKUP_OBJECT (parky, label48, "label48");
  GLADE_HOOKUP_OBJECT (parky, button_modif_modif, "button_modif_modif");
  GLADE_HOOKUP_OBJECT (parky, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (parky, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (parky, image14, "image14");
  GLADE_HOOKUP_OBJECT (parky, label33, "label33");
  GLADE_HOOKUP_OBJECT (parky, label4, "label4");
  GLADE_HOOKUP_OBJECT (parky, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (parky, entry_idp_delete, "entry_idp_delete");
  GLADE_HOOKUP_OBJECT (parky, label37, "label37");
  GLADE_HOOKUP_OBJECT (parky, button_deletep_delete, "button_deletep_delete");
  GLADE_HOOKUP_OBJECT (parky, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (parky, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (parky, image19, "image19");
  GLADE_HOOKUP_OBJECT (parky, label38, "label38");
  GLADE_HOOKUP_OBJECT (parky, button_cancelp_delete, "button_cancelp_delete");
  GLADE_HOOKUP_OBJECT (parky, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (parky, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (parky, image20, "image20");
  GLADE_HOOKUP_OBJECT (parky, label39, "label39");
  GLADE_HOOKUP_OBJECT (parky, image30, "image30");
  GLADE_HOOKUP_OBJECT (parky, search_yosr_delete, "search_yosr_delete");
  GLADE_HOOKUP_OBJECT (parky, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (parky, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (parky, image26, "image26");
  GLADE_HOOKUP_OBJECT (parky, label46, "label46");
  GLADE_HOOKUP_OBJECT (parky, label5, "label5");
  GLADE_HOOKUP_OBJECT (parky, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (parky, label_affect_agent, "label_affect_agent");
  GLADE_HOOKUP_OBJECT (parky, label41, "label41");
  GLADE_HOOKUP_OBJECT (parky, combo_yosr_parking, "combo_yosr_parking");
  GLADE_HOOKUP_OBJECT (parky, label42, "label42");
  GLADE_HOOKUP_OBJECT (parky, image22, "image22");
  GLADE_HOOKUP_OBJECT (parky, button_affect_affect, "button_affect_affect");
  GLADE_HOOKUP_OBJECT (parky, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (parky, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (parky, image23, "image23");
  GLADE_HOOKUP_OBJECT (parky, label43, "label43");
  GLADE_HOOKUP_OBJECT (parky, button_cancelp_cancel, "button_cancelp_cancel");
  GLADE_HOOKUP_OBJECT (parky, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (parky, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (parky, image24, "image24");
  GLADE_HOOKUP_OBJECT (parky, label44, "label44");
  GLADE_HOOKUP_OBJECT (parky, refresh_yosr3, "refresh_yosr3");
  GLADE_HOOKUP_OBJECT (parky, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (parky, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (parky, image34, "image34");
  GLADE_HOOKUP_OBJECT (parky, label49, "label49");
  GLADE_HOOKUP_OBJECT (parky, image35, "image35");
  GLADE_HOOKUP_OBJECT (parky, combo_yosr_agent, "combo_yosr_agent");
  GLADE_HOOKUP_OBJECT (parky, label6, "label6");

  return parky;
}

